<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-I14BVK5" ignored="0" name="Test" tests="10" failures="1" timestamp="2022-05-25T00:46:00 IST" time="14.71" errors="0">
  <testcase name="Testcase1" time="6.59" classname="org.testing.Testscripts.TC1_PostRequest"/>
  <testcase name="Testcase2" time="0.094" classname="org.testing.Testscripts.TC2_Getrequest"/>
  <testcase name="TC3" time="1.181" classname="org.testing.Testscripts.TC3_Getallrequest"/>
  <testcase name="Put" time="0.063" classname="org.testing.Testscripts.TC4_Putrequest"/>
  <testcase name="Delete" time="0.051" classname="org.testing.Testscripts.TC5_Deleterequest"/>
  <testcase name="deletenew" time="1.408" classname="org.testing.Testscripts.TC10_Deletenew"/>
  <testcase name="create" time="1.308" classname="org.testing.Testscripts.TC6_Createrecord"/>
  <testcase name="getemployee" time="1.372" classname="org.testing.Testscripts.TC7_Getemployee">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at org.testing.utilities.Parsingjsonusingpath.jsonpath(Parsingjsonusingpath.java:9)
at org.testing.responsevalidation.Responsevalidate.Data(Responsevalidate.java:13)
at org.testing.Testscripts.TC7_Getemployee.getemployee(TC7_Getemployee.java:27)
at java.util.ArrayList.forEach(Unknown Source)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 34 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- getemployee -->
  <testcase name="ALLDATA" time="1.342" classname="org.testing.Testscripts.TC8_Alldataget"/>
  <testcase name="putupdate" time="1.197" classname="org.testing.Testscripts.TC9_Update"/>
</testsuite> <!-- Test -->
